version: "3"
services:
  server:
    build: ./server
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
      bundle exec rails server -b 0.0.0.0"
    volumes:
      - ./server:/myapp/server
      - bundle_path:/myapp/server/bundle
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      - BUNDLE_PATH=/myapp/server/bundle
    depends_on:
      - postgres
  postgres:
    image: "postgres:11-alpine"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - server_db:/var/lib/postgresql/data
  client:
    build: ./client
    command: "npm run start"
    volumes:
      - ./client:/myapp/client
      - /myapp/client/node_modules
    ports:
      - "${CLIENT_PORT}:3000"
volumes:
  server_db:
  bundle_path:
